include("gaussianVMF.jl")
include("gaussianVMFmixture.jl")
include("uniformPose.jl")
include("beta_array.jl")
include("bernoulli_array.jl")
# include("voxel_binary_latent_likelihood.jl")
include("uniform_mixture_from_template.jl")
